/*
 * MOTOR.c
 *
 * Created: 3/6/2021 3:54:31 PM
 *  Author: Abdelrahman
 */ 
#include "MOTOR.h"

void MOTOR1_Init	(void){
	
		DIO_SETPIN_DIRECTION(MOTOR_CNTRL_PORT,MOTOR_EN1,MOTOR_OUTPUT);
		DIO_SETPIN_DIRECTION(MOTOR_DTA_PORT,MOTOR1_A1,MOTOR_OUTPUT);
		DIO_SETPIN_DIRECTION(MOTOR_DTA_PORT,MOTOR1_A2,MOTOR_OUTPUT);
	
}

void MOTOR1_ENABLE  (void){
	
	DIO_SETPIN_VALUE(MOTOR_CNTRL_PORT,MOTOR_EN1,MOTOR_HIGH);
	
}

void MOTOR1_DISABLE (void){
	
		DIO_SETPIN_VALUE(MOTOR_CNTRL_PORT,MOTOR_EN1,MOTOR_LOW);
	
}

void MOTOR1_CW		(void){
	
		DIO_SETPIN_VALUE(MOTOR_DTA_PORT,MOTOR1_A1,MOTOR_HIGH);
		DIO_SETPIN_VALUE(MOTOR_DTA_PORT,MOTOR1_A2,MOTOR_LOW);
	
}

void MOTOR1_CCW		(void){
	
			DIO_SETPIN_VALUE(MOTOR_DTA_PORT,MOTOR1_A1,MOTOR_LOW);
			DIO_SETPIN_VALUE(MOTOR_DTA_PORT,MOTOR1_A2,MOTOR_HIGH);
	
}